// Medication-specific questions for prior authorization
export const medicationQuestions: { [key: string]: string[] } = {
  ozempic: [
    "What is the patient's current A1C level?",
    'What is their BMI?',
    'Have they tried metformin? For how long?',
    'Any GI side effects with metformin?',
    'Have they tried other oral diabetes medications?',
    'Any contraindications to sulfonylureas?',
    'Is there a history of pancreatitis?',
    'Any thyroid cancer in family history?',
    'Current kidney function (eGFR)?',
    'Are they on insulin currently?',
  ],
  farxiga: [
    'Current A1C level?',
    'eGFR/kidney function?',
    'History of UTIs or genital infections?',
    'Current metformin dose?',
    'History of diabetic ketoacidosis?',
    'Blood pressure readings?',
    'Heart failure status?',
    'Volume depletion risk?',
    'Other SGLT2 inhibitors tried?',
    'Planned surgeries?',
  ],
  jardiance: [
    'Current A1C and duration of diabetes?',
    'Cardiovascular disease history?',
    'Heart failure classification if applicable?',
    'Current kidney function (eGFR)?',
    'History of genital mycotic infections?',
    'Current blood pressure?',
    'Metformin tolerance?',
    'History of ketoacidosis?',
    'Volume status/dehydration risk?',
    'Other diabetes medications?',
  ],
  lantus: [
    'Current A1C level?',
    'Fasting glucose levels?',
    'Previous basal insulin use?',
    'Total daily insulin requirements?',
    'Hypoglycemia frequency?',
    'Current oral diabetes medications?',
    'Meal schedule consistency?',
    'Injection site reactions?',
    'Insurance formulary preference?',
    'Patient preference for dosing?',
  ],
  toujeo: [
    'Current Lantus dose if switching?',
    'A1C and glucose control?',
    'Hypoglycemia episodes on current regimen?',
    'Why switching from current insulin?',
    'Total daily insulin units?',
    'Injection technique issues?',
    'Cost considerations?',
    'Travel/storage needs?',
    'Concentrated insulin experience?',
    'Target A1C goal?',
  ],
  dexcom: [
    'Type 1 or Type 2 diabetes?',
    'Current A1C level?',
    'Frequency of hypoglycemia?',
    'Hypoglycemia unawareness?',
    'Current glucose monitoring frequency?',
    'Insulin regimen (MDI or pump)?',
    'Previous CGM use?',
    'Smartphone compatibility?',
    'Caregiver monitoring needs?',
    'Insurance DME or pharmacy benefit?',
  ],
  libre: [
    'Diabetes type and duration?',
    'Current fingerstick frequency?',
    'A1C level?',
    'Insulin regimen details?',
    'Hypoglycemia frequency/severity?',
    'Previous CGM experience?',
    'Skin sensitivity issues?',
    'Water exposure needs?',
    'Reading device preference?',
    'Cost considerations?',
  ],
  prolia: [
    'Bone density T-score?',
    'Previous fracture history?',
    'Failed bisphosphonates? Which ones?',
    'Calcium and Vitamin D levels?',
    'Dental exam completed?',
    'Kidney function?',
    'Hypocalcemia risk?',
    'Immunosuppression status?',
    'Planned dental procedures?',
    'Previous Prolia doses?',
  ],
  forteo: [
    'Osteoporosis severity (T-score)?',
    'Previous fractures?',
    'Failed other osteoporosis treatments?',
    "Paget's disease ruled out?",
    'Prior radiation therapy?',
    'Hypercalcemia history?',
    'Kidney stones?',
    'Duration of treatment planned?',
    'Bone cancer risk factors?',
    'Current calcium/Vitamin D?',
  ],
  tymlos: [
    'Postmenopausal osteoporosis confirmed?',
    'T-score and fracture history?',
    'Why not bisphosphonates?',
    'Previous anabolic agent use?',
    'Orthostatic hypotension?',
    'Heart rate issues?',
    'Kidney function?',
    'Hypercalcemia history?',
    'Treatment duration planned?',
    'Injection training needed?',
  ],
  lispro: [
    'Mealtime glucose control?',
    'Carb counting ability?',
    'Current rapid insulin if any?',
    'Insulin-to-carb ratios?',
    'Correction factor?',
    'Hypoglycemia frequency?',
    'Meal timing consistency?',
    'Why lispro vs other rapid?',
    'Insurance formulary?',
    'Pen vs vial preference?',
  ],
  humalog: [
    'Current rapid-acting insulin?',
    'Pre-meal glucose readings?',
    'Post-meal glucose spikes?',
    'Carbohydrate counting skills?',
    'Insulin sensitivity factor?',
    'Timing of insulin with meals?',
    'Hypoglycemia patterns?',
    'Why switching to Humalog?',
    'Delivery device preference?',
    'Insurance coverage tier?',
  ],
  wegovy: [
    "What is the patient's current BMI?",
    'What is their weight and height?',
    'Any weight-related comorbidities (diabetes, hypertension, sleep apnea)?',
    'Previous weight loss attempts (diet, exercise programs)?',
    'Have they tried other weight loss medications?',
    'Any history of eating disorders?',
    'History of pancreatitis or gallbladder disease?',
    'Thyroid cancer in family?',
    'Current cardiovascular status?',
    'Any planned surgeries?',
  ],
  mounjaro: [
    'Current A1C level?',
    'How long have they had type 2 diabetes?',
    'Current medications for diabetes?',
    'Have they failed metformin? Why?',
    'Previous GLP-1 agonist use?',
    'Any DPP-4 inhibitor use?',
    'History of diabetic retinopathy?',
    'Kidney function (eGFR)?',
    'History of pancreatitis?',
    'Current insulin regimen if applicable?',
  ],
  saxenda: [
    'Current BMI?',
    'Previous weight loss attempts documented?',
    'Duration of obesity?',
    'Comorbid conditions?',
    'Previous bariatric surgery considered?',
    'Current medications?',
    'History of depression or suicidal ideation?',
    'Thyroid issues?',
    'Heart rate concerns?',
    'Pregnancy plans?',
  ],
  trulicity: [
    'Current A1C?',
    'Duration of diabetes?',
    'Metformin tolerance and dose?',
    'Other diabetes medications tried?',
    'Cardiovascular history?',
    'Kidney function?',
    'History of pancreatitis?',
    'Gastroparesis symptoms?',
    'Thyroid nodules or cancer history?',
    'Injection site reactions with other meds?',
  ],
  humira: [
    "Specific diagnosis (RA, Crohn's, UC, Psoriasis)?",
    'Disease severity score?',
    'Previous DMARDs tried?',
    'How long on methotrexate?',
    'Response to previous treatments?',
    'Current symptoms affecting daily life?',
    'TB test results?',
    'Hepatitis B and C screening?',
    'Recent infections?',
    'Live vaccines needed?',
  ],
  enbrel: [
    'Diagnosis and severity?',
    'Failed conventional DMARDs?',
    'Methotrexate dose and duration?',
    'Joint count affected?',
    'Morning stiffness duration?',
    'Functional impairment level?',
    'TB screening completed?',
    'Recent infections or surgeries?',
    'History of cancer?',
    'Neurological symptoms?',
  ],
  remicade: [
    'Specific inflammatory condition?',
    'Disease activity score?',
    'Endoscopy/colonoscopy findings?',
    'Failed conventional therapy details?',
    'Hospitalization history?',
    'Steroid dependency?',
    'TB test and chest X-ray results?',
    'Hepatitis screening?',
    'History of heart failure?',
    'Infusion reaction history?',
  ],
  stelara: [
    "Diagnosis (Psoriasis, Crohn's, UC)?",
    'Body surface area affected (if psoriasis)?',
    'Previous biologic use?',
    'Response to TNF inhibitors?',
    'Current disease activity?',
    'Quality of life impact?',
    'TB screening results?',
    'Recent vaccinations?',
    'History of malignancy?',
    'Current infections?',
  ],
  cosentyx: [
    'Psoriasis or psoriatic arthritis?',
    'PASI score or BSA affected?',
    'Failed treatments list?',
    'Previous biologic response?',
    'Joint involvement?',
    'Impact on daily activities?',
    'TB test results?',
    'IBD history?',
    'Recent infections?',
    'Vaccination status?',
  ],
  dupixent: [
    'Atopic dermatitis or asthma?',
    'Disease severity (IGA score)?',
    'Body surface area affected?',
    'Failed topical treatments?',
    'Systemic therapy history?',
    'Impact on sleep/daily life?',
    'Eye problems history?',
    'Parasitic infection risk?',
    'Eosinophil count?',
    'Pregnancy/breastfeeding?',
  ],
  xeljanz: [
    'RA severity and duration?',
    'Failed DMARDs (which ones)?',
    'Failed biologics?',
    'Current disease activity score?',
    'Joint damage on X-ray?',
    'CV risk factors?',
    'History of blood clots?',
    'Recent CBC and liver tests?',
    'History of diverticulitis?',
    'Vaccination status?',
  ],
  otezla: [
    'Psoriasis or psoriatic arthritis?',
    'Previous treatments tried?',
    'Why did previous treatments fail?',
    'Current disease severity?',
    'Joint involvement?',
    'Depression history?',
    'Weight changes recently?',
    'GI symptoms?',
    'Kidney function?',
    'Drug interactions?',
  ],
  taltz: [
    'Plaque psoriasis or psoriatic arthritis?',
    'BSA or PASI score?',
    'Previous systemic therapy?',
    'Biologic failure history?',
    'Quality of life impact?',
    'TB screening done?',
    'IBD history or risk?',
    'Recent infections?',
    'Vaccination needs?',
    'Injection site reactions before?',
  ],
  skyrizi: [
    'Psoriasis severity metrics?',
    'Failed treatments (topical, oral, biologics)?',
    'Why did previous treatments fail?',
    'Impact on work/social life?',
    'Skin areas most affected?',
    'TB test results?',
    'Hepatitis screening?',
    'History of infections?',
    'Current vaccinations?',
    'Pregnancy considerations?',
  ],
};

// Helper function to get questions for a medication
export function getQuestionsForMedication(medication: string): string[] {
  const med = medication.toLowerCase();
  return medicationQuestions[med] || [];
}

// Check if medication needs prior auth
export function needsPriorAuth(medication: string): boolean {
  return medication.toLowerCase() in medicationQuestions;
}
