/**
 * 🔒 PROTECTED SERVICE - DICTATION V1
 *
 * ⛔ DO NOT MODIFY THIS FILE
 * Status: PRODUCTION STABLE (8/29/2025)
 *
 * This service contains the WORKING dictation configuration.
 * Any changes should be made in a V2 copy, not here.
 */

export const DICTATION_V1_CONFIG = {
  // AWS Transcribe Configuration (LOCKED)
  transcribe: {
    Type: 'DICTATION',
    ShowSpeakerLabels: false,
    ContentIdentificationType: 'PHI',
    Specialty: 'PRIMARYCARE',
    LanguageCode: 'en-US',
    MediaSampleRateHertz: 16000,
    MediaEncoding: 'pcm',
  },

  // Bedrock AI Configuration (LOCKED)
  bedrock: {
    modelId: 'anthropic.claude-3-5-sonnet-20240620-v1:0',
    fallbackModelId: 'anthropic.claude-3-sonnet-20240229-v1:0',
    maxTokens: 4096,
    temperature: 0.3,
    topP: 0.95,
  },

  // Clinical Note Prompt (LOCKED)
  prompt: `You are a medical scribe for an endocrinologist. Convert the following medical dictation into a structured, professional clinical note.

Format the note with these sections:
- CHIEF COMPLAINT
- HISTORY OF PRESENT ILLNESS
- REVIEW OF SYSTEMS
- PAST MEDICAL HISTORY
- MEDICATIONS
- ALLERGIES
- SOCIAL HISTORY
- FAMILY HISTORY
- PHYSICAL EXAMINATION
- DIAGNOSTIC RESULTS
- ASSESSMENT (numbered list of diagnoses)
- PLAN (numbered list with specific actions)

Important:
1. Use proper medical terminology
2. Be concise but complete
3. Include all mentioned lab values and measurements
4. Format lists with numbers or bullets as appropriate
5. If information for a section is not provided, leave the section header with no content
6. Pay special attention to endocrinology-related terms and values

The dictation to process is:`,

  // Note Header Template (LOCKED)
  noteHeader: (patientName: string, mrn: string, date: string) => `CLINICAL NOTE - ENDOCRINOLOGY
====================
Patient: ${patientName || 'Unknown Patient'}
MRN: ${mrn || 'Unknown MRN'}
Date: ${date}
Provider: Dr. Rakesh Patel, MD - Endocrinologist

`,

  // Note Footer Template (LOCKED)
  noteFooter: (timestamp: string) => `
====================
Generated by AWS Bedrock Claude 3.5 Sonnet (HIPAA Compliant)
Processed: ${timestamp}`,

  // Medical Corrections (LOCKED)
  medicalTerms: {
    // Endocrinology specific terms
    'hemoglobin a1c': 'Hemoglobin A1c',
    hba1c: 'HbA1c',
    tsh: 'TSH',
    t3: 'T3',
    t4: 'T4',
    'free t4': 'Free T4',
    'free t3': 'Free T3',
    glucose: 'glucose',
    insulin: 'insulin',
    metformin: 'metformin',
    levothyroxine: 'levothyroxine',
    synthroid: 'Synthroid',
    goiter: 'goiter',
    thyroid: 'thyroid',
    diabetes: 'diabetes',
    diabetic: 'diabetic',
    hypoglycemia: 'hypoglycemia',
    hyperglycemia: 'hyperglycemia',
    hypothyroid: 'hypothyroid',
    hyperthyroid: 'hyperthyroid',
    thyroidectomy: 'thyroidectomy',
    endocrine: 'endocrine',
    pituitary: 'pituitary',
    adrenal: 'adrenal',
    cortisol: 'cortisol',
    acth: 'ACTH',
    prolactin: 'prolactin',
    testosterone: 'testosterone',
    estrogen: 'estrogen',
    parathyroid: 'parathyroid',
    calcium: 'calcium',
    'vitamin d': 'vitamin D',
    osteoporosis: 'osteoporosis',
    cushings: "Cushing's",
    addisons: "Addison's",
    graves: "Graves'",
    hashimotos: "Hashimoto's",
  },
};

/**
 * Get the locked configuration
 * This ensures no accidental modifications
 */
export function getLockedDictationConfig() {
  // Return a frozen copy to prevent modifications
  return Object.freeze(JSON.parse(JSON.stringify(DICTATION_V1_CONFIG)));
}

/**
 * Validate that current config matches locked config
 * Use this to detect unauthorized changes
 */
export function validateDictationConfig(currentConfig: any): boolean {
  const locked = getLockedDictationConfig();
  return JSON.stringify(currentConfig) === JSON.stringify(locked);
}
