#!/bin/bash

# TSHLA Medical - Simple Migration Helper
# This script helps you complete the Supabase migration

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  TSHLA Medical - Migration Helper                        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

echo "🎯 You've already started the migration!"
echo "   Error: trigger already exists = Good progress!"
echo ""
echo "📋 What to do now:"
echo ""
echo "The SQL file has already been partially run. Some items exist,"
echo "others need to be created. Here's the easiest way:"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "OPTION 1: Continue in Supabase Dashboard (Recommended)"
echo "─────────────────────────────────────────────────────────"
echo "The SQL uses 'IF NOT EXISTS' so it's safe to run again!"
echo ""
echo "1. You're already in Supabase SQL Editor (good!)"
echo "2. CLEAR the editor (Cmd+A, then Delete)"
echo "3. Open the SQL file again:"
echo "   "
echo "   In Finder: Desktop → tshla-medical → database → migrations"
echo "              → dictated-notes-schema.sql"
echo ""
echo "4. Select ALL (Cmd+A), Copy (Cmd+C)"
echo "5. Paste in Supabase (Cmd+V)"
echo "6. Click RUN"
echo "7. Ignore 'already exists' errors - they're OK!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "OPTION 2: Quick Terminal Command"
echo "─────────────────────────────────────────────────────────"
echo "Run this command to open the file:"
echo ""
echo "  open database/migrations/dictated-notes-schema.sql"
echo ""
echo "Then copy/paste into Supabase as described above."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "OPTION 3: Check What's Already Done"
echo "─────────────────────────────────────────────────────────"
echo "Run this to see what tables exist:"
echo ""
echo "  node scripts/verify-migration.js"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 TIP: The 'already exists' errors are GOOD!"
echo "   They mean those parts were successfully created."
echo "   Just run it again - it will skip what exists and"
echo "   create what's missing."
echo ""
echo "Questions?"
echo "  Check: DICTATION_STORAGE_COMPLETE.md"
echo ""
