name: Deploy Auth API to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - 'server/medical-auth-api.js'
      - 'server/services/**'
      - 'server/utils/**'
      - 'server/package.json'
      - 'server/Dockerfile.auth'
      - '.github/workflows/deploy-auth-api-container.yml'
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: tshlaregistry.azurecr.io
  CONTAINER_APP_NAME: tshla-auth-api-container
  RESOURCE_GROUP: tshla-backend-rg
  IMAGE_NAME: tshla-auth-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      working-directory: ./server
      run: |
        # Login to ACR
        az acr login --name tshlaregistry

        # Build and tag image
        docker build -f Dockerfile.auth -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker tag ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

        # Push image to ACR
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Container App URL: https://tshla-auth-api-container.redpebble-e4551b7a.eastus.azurecontainerapps.io"

        # Wait a moment for deployment to stabilize
        sleep 10

        # Test the health endpoint
        curl -f https://tshla-auth-api-container.redpebble-e4551b7a.eastus.azurecontainerapps.io/health || echo "Health check failed - container may still be starting"
